// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJlOlge0_vUyzTvV9G_1EW2Bgs_DZnUU',
    appId: '1:1043167775270:web:636a61be9fecd8e7d234e7',
    messagingSenderId: '1043167775270',
    projectId: 'final-project-57aa2',
    authDomain: 'final-project-57aa2.firebaseapp.com',
    storageBucket: 'final-project-57aa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNK174AREEXNOlepYe5kO9h_WQxTzIxg',
    appId: '1:1043167775270:android:b2a71c26bc22de80d234e7',
    messagingSenderId: '1043167775270',
    projectId: 'final-project-57aa2',
    storageBucket: 'final-project-57aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClvFssRtvUSC7WvpckxlfLmQefr-91xXM',
    appId: '1:1043167775270:ios:de95881636a62918d234e7',
    messagingSenderId: '1043167775270',
    projectId: 'final-project-57aa2',
    storageBucket: 'final-project-57aa2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClvFssRtvUSC7WvpckxlfLmQefr-91xXM',
    appId: '1:1043167775270:ios:de95881636a62918d234e7',
    messagingSenderId: '1043167775270',
    projectId: 'final-project-57aa2',
    storageBucket: 'final-project-57aa2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJlOlge0_vUyzTvV9G_1EW2Bgs_DZnUU',
    appId: '1:1043167775270:web:5de3e3edd58a563ad234e7',
    messagingSenderId: '1043167775270',
    projectId: 'final-project-57aa2',
    authDomain: 'final-project-57aa2.firebaseapp.com',
    storageBucket: 'final-project-57aa2.firebasestorage.app',
  );
}
